{{- if .Values.delegatedAgentDeployment.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agent.configmapName" . | printf "%s-deployment" | trunc 63 | trimSuffix "-" }}
  namespace: {{ include "agent.namespace" . }}
  labels:
{{ include "agent.labels" . | indent 4 }}
data:
  dragent.yaml: |
    new_k8s: true
{{- include "agent.clusterName" . | trim | nindent 4 }}
{{- include "agent.connectionSettings" . | trim | nindent 4 }}
    feature:
      mode: monitor_light
    cointerface_enabled: true
    k8s_delegated_nodes: {{ .Values.delegatedAgentDeployment.delegated_nodes | int }}
    top_processes_in_sample: 0
    container_engines:
      bpm: false
      cri: false
      docker: false
      libvirt_lxc: false
      lxc: false
      mesos: false
      podman: false
      rkt: false
    app_checks_enabled: false
    jmx:
      enabled: false
    prometheus:
      enabled: false
    statsd:
      enabled: false
{{- include "agent.k8sColdStart" . | nindent 4 }}
{{ include "agent.disableCaptures" . | nindent 4 }}
{{- $_ := mergeOverwrite .Values.secure (dict "enabled" false) }}
{{- (include "agent.secureFeatures" .) | nindent 4 }}
{{- include "agent.logSettings" . }}
{{- if .Values.global.sysdig.tags }}
    tags: {{ include "agent.tags" . }}
{{- end }}
{{/*
  Checking here the user is using Custom CA and if http_proxy.ssl = true
  If these conditions are true, then we use the agent.sslCaFileName for the http_proxy.ca_certificate
*/}}
{{- if and (include "agent.printCA" .) (.Values.sysdig.settings) (hasKey .Values.sysdig.settings "http_proxy") (hasKey .Values.sysdig.settings.http_proxy "ssl") (eq (get .Values.sysdig.settings.http_proxy "ssl") true) }}
  {{- $baseSettings := .Values.sysdig.settings -}}
  {{- $caFileName := include "agent.sslCaFileName" . }}
  {{- $caFilePath := printf "%s%s" "/ca-certs/" $caFileName }}
  {{- $mergedSettings := mergeOverwrite $baseSettings (dict "http_proxy" (dict "ca_certificate" $caFilePath)) -}}
  {{ toYaml $mergedSettings | indent 4 }}
{{- else if .Values.sysdig.settings }}
  {{ toYaml .Values.sysdig.settings | indent 4 }}
{{- end }}
{{- end }}
